<a href="https://colab.research.google.com/github/Restara/Data-Mining/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
dataset = pd.read_csv('Sepatu.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [23]:
print(x)

[['Converse' 20.0 530000.0]
 ['Adidas' 27.0 499000.0]
 ['Adidas' 0.0 825000.0]
 ['Adidas' 0.0 480000.0]
 ['Converse' 10.0 899000.0]
 ['Eagle' 17.0 nan]
 ['Nike' 0.0 1500000.0]
 ['Eagle' nan 400000.0]
 ['Converse' 0.0 133000.0]
 ['Eagle' nan nan]]


In [24]:
print(y)

['Ready' 'Ready' 'Sold' 'Sold' 'Ready' 'Ready' 'Sold' 'Ready' 'Sold'
 'Ready']


In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [26]:
print(x)

[['Converse' 20.0 530000.0]
 ['Adidas' 27.0 499000.0]
 ['Adidas' 0.0 825000.0]
 ['Adidas' 0.0 480000.0]
 ['Converse' 10.0 899000.0]
 ['Eagle' 17.0 658250.0]
 ['Nike' 0.0 1500000.0]
 ['Eagle' 9.25 400000.0]
 ['Converse' 0.0 133000.0]
 ['Eagle' 9.25 658250.0]]


In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [28]:
print(x)

[[0.0 1.0 0.0 0.0 20.0 530000.0]
 [1.0 0.0 0.0 0.0 27.0 499000.0]
 [1.0 0.0 0.0 0.0 0.0 825000.0]
 [1.0 0.0 0.0 0.0 0.0 480000.0]
 [0.0 1.0 0.0 0.0 10.0 899000.0]
 [0.0 0.0 1.0 0.0 17.0 658250.0]
 [0.0 0.0 0.0 1.0 0.0 1500000.0]
 [0.0 0.0 1.0 0.0 9.25 400000.0]
 [0.0 1.0 0.0 0.0 0.0 133000.0]
 [0.0 0.0 1.0 0.0 9.25 658250.0]]


In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [30]:
print(y)

[0 0 1 1 0 0 1 0 1 0]


In [31]:
from sklearn.model_selection import  train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [32]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 1500000.0]
 [0.0 1.0 0.0 0.0 10.0 899000.0]
 [0.0 1.0 0.0 0.0 20.0 530000.0]
 [1.0 0.0 0.0 0.0 0.0 480000.0]
 [1.0 0.0 0.0 0.0 27.0 499000.0]
 [0.0 0.0 1.0 0.0 9.25 400000.0]
 [0.0 1.0 0.0 0.0 0.0 133000.0]
 [0.0 0.0 1.0 0.0 17.0 658250.0]]


In [33]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 825000.0]
 [0.0 0.0 1.0 0.0 9.25 658250.0]]


In [34]:
print(y_train)

[1 0 0 1 0 0 1 0]


In [35]:
print(y_test)

[1 0]


In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [37]:
print(x_train)

[[0.0 0.0 0.0 2.6457513110645903 -1.0840121729436925 2.2467738588462063]
 [0.0 1.0 0.0 -0.3779644730092272 -0.04231879353834235 0.6813659374851138]
 [0.0 1.0 0.0 -0.3779644730092272 0.9993745858670078 -0.2797580608214474]
 [1.0 0.0 0.0 -0.3779644730092272 -1.0840121729436925
  -0.40999166492802747]
 [1.0 0.0 0.0 -0.3779644730092272 1.7285599514507528 -0.36050289536752705]
 [0.0 0.0 1.0 -0.3779644730092272 -0.12044579699374361
  -0.6183654314985556]
 [0.0 1.0 0.0 -0.3779644730092272 -1.0840121729436925 -1.3138128774276934]
 [0.0 0.0 1.0 -0.3779644730092272 0.6868665720454027 0.054291133711930575]]


In [38]:
print(x_test)

[[1.0 0.0 0.0 -0.3779644730092272 -1.0840121729436925 0.4886202034073752]
 [0.0 0.0 1.0 -0.3779644730092272 -0.12044579699374361
  0.054291133711930575]]
